hatoffsetindex = {}
hatoffsetindex["idleanim"] = "idle"
hatoffsetindex["run"] = "running"
hatoffsetindex["runfast"] = "running"
hatoffsetindex["slide"] = "sliding"
hatoffsetindex["jump"] = "jumping"
hatoffsetindex["fall"] = "falling"
hatoffsetindex["climb"] = "climbing"
hatoffsetindex["swim"] = "swimming"
hatoffsetindex["swimpush"] = "swimming"
hatoffsetindex["duck"] = "ducking"
hatoffsetindex["fly"] = "flyjump"
hatoffsetindex["capefly"] = "capefly"
hatoffsetindex["float"] = "jumping"
hatoffsetindex["die"] = "dead"
hatoffsetindex["grownogun"] = "grow"

hatoffsets = {}
hatoffsets["idle"] = {0, 0}
hatoffsets["running"] = {{0, 0}, {0, 0}, {-1, -1}}
hatoffsets["sliding"] = {0, 0}
hatoffsets["jumping"] = {0, -1}
hatoffsets["falling"] = {0, 0}
hatoffsets["climbing"] = {{0, 0}, {0, -1}}
hatoffsets["fence"] = {{0, 0}, {0, 0}}
hatoffsets["swimming"] = {{1, -1}, {1, -1}, {1, -1}, {1, -1}, {1, -1}}
hatoffsets["ducking"] = {0, -3}
hatoffsets["dead"] = {1, -2}
hatoffsets["grow"] = {-6, 0}

bighatoffsets = {}
bighatoffsets["idle"] = {-4, -2}
bighatoffsets["fire"] = {-5, -4}
bighatoffsets["running"] = {{-5, -4}, {-4, -3}, {-3, -2}}
bighatoffsets["sliding"] = {-5, -2}
bighatoffsets["jumping"] = {-4, -4}
bighatoffsets["falling"] = {-4, -2}
bighatoffsets["climbing"] = {{-4, -4}, {-4, -4}}
bighatoffsets["fence"] = {{-4, -4}, {-4, -4}}
bighatoffsets["swimming"] = {{-5, -4}, {-5, -4}, {-5, -4}, {-5, -4}, {-5, -4}}
bighatoffsets["ducking"] = {-5, -12}
bighatoffsets["flyjump"] = {-4, -2}
bighatoffsets["capefly"] = {{-10, -10}, {-11, -15}, {-10, -19}, {-11, -21}, {-9, -22}, {-9, -24}}
bighatoffsets["dead"] = false

skinnyhatoffsets = {}
skinnyhatoffsets["idle"] = {1, 0}
skinnyhatoffsets["running"] = {{2, -2}, {1, -1}, {3, 0}}
skinnyhatoffsets["sliding"] = {-1, -3}
skinnyhatoffsets["jumping"] = {2, -2}
skinnyhatoffsets["falling"] = {1, 0}
skinnyhatoffsets["climbing"] = {{2, 0}, {4, -2}}
skinnyhatoffsets["fence"] = {{2, 0}, {2, 0}}
skinnyhatoffsets["swimming"] = {{0, 0}, {0, -1}, {-2, -1}, {0, -1}, {0, -1}}
skinnyhatoffsets["ducking"] = {1, -13}
skinnyhatoffsets["dead"] = false

skinnyhat = {}
