name = "mari0_ae"
default_targets = ["win32", "win64", "appimage", "macos"]
build_directory = "makelove-build"
icon_file = "graphics/icon.png"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

# TODO: more metadata

[windows.exe_metadata]
ProductName = "Mari0: AE"

[linux.desktop_file_metadata]
Name = "Mari0: AE"

[macos.app_metadata]
CFBundleDisplayName = "Mari0: AE"
