name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags, e.g., v1.0, v1.1.0

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    needs: build  # Ensure this job runs after the "Compile" job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Rename Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-linux
          path: ./artifacts
      - run: mv ./artifacts/mari0_ae-linux ./artifacts/alesan99s_entities_${{ github.ref_name }}.AppImage

      - name: Download and Rename macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-macos
          path: ./artifacts
      - run: mv ./artifacts/mari0_ae-macos ./artifacts/alesan99s_entities_${{ github.ref_name }}-macos.zip

      - name: Download and Rename Windows 64-bit Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-win64
          path: ./artifacts
      - run: mv ./artifacts/mari0_ae-win64 ./artifacts/alesan99s_entities_${{ github.ref_name }}-win64.zip

      - name: Download and Rename Windows 32-bit Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-win32
          path: ./artifacts
      - run: mv ./artifacts/mari0_ae-win32 ./artifacts/alesan99s_entities_${{ github.ref_name }}-win32.zip

      - name: Download and Rename Android Release APK
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-android-release
          path: ./artifacts
      - run: mv ./artifacts/${{ github.event.repository.name }}-android-release ./artifacts/alesan99s_entities_${{ github.ref_name }}.apk

      - name: Download and Rename Source Code Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-source
          path: ./artifacts
      - run: mv ./artifacts/${{ github.event.repository.name }}-source ./artifacts/alesan99s_entities_${{ github.ref_name }}-source.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Artifact
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./artifacts/alesan99s_entities_${{ github.ref_name }}.AppImage
          asset_name: alesan99s_entities_${{ github.ref_name }}.AppImage
          asset_content_type: application/x-executable

      - name: Upload macOS Artifact
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./artifacts/alesan99s_entities_${{ github.ref_name }}-macos.zip
          asset_name: alesan99s_entities_${{ github.ref_name }}-macos.zip
          asset_content_type: application/zip

      - name: Upload Windows 64-bit Artifact
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./artifacts/alesan99s_entities_${{ github.ref_name }}-win64.zip
          asset_name: alesan99s_entities_${{ github.ref_name }}-win64.zip
          asset_content_type: application/zip

      - name: Upload Windows 32-bit Artifact
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./artifacts/alesan99s_entities_${{ github.ref_name }}-win32.zip
          asset_name: alesan99s_entities_${{ github.ref_name }}-win32.zip
          asset_content_type: application/zip

      - name: Upload Android Release APK
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./artifacts/alesan99s_entities_${{ github.ref_name }}.apk
          asset_name: alesan99s_entities_${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Source Code
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./artifacts/alesan99s_entities_${{ github.ref_name }}-source.zip
          asset_name: alesan99s_entities_${{ github.ref_name }}-source.zip
          asset_content_type: application/zip
